#!/usr/bin/env bash
# Heirloom - one-time TTS sidecar install for the desktop bundle.
#
# Sets up a Python venv under the user's Application Support, installs
# LuxTTS + dependencies, and seeds a launcher script. Heirloom's Rust
# shell looks for this venv at startup and spawns the sidecar if it
# exists; otherwise the app runs without voice cloning/playback.
#
# Run once after installing Heirloom.app:
#   /Applications/Heirloom.app/Contents/Resources/tts/install-tts.sh
#
# Footprint: ~2 GB (torch, audio libs, ZipVoice model on first request).

set -euo pipefail

heading() { printf "\n\033[1;35m=== %s ===\033[0m\n" "$1"; }
ok()      { printf "  \033[32mok\033[0m  %s\n" "$1"; }
fail()    { printf "  \033[31m!!\033[0m  %s\n" "$1" >&2; exit 1; }

# Resolve the bundled tts source directory (sibling of this script).
TTS_SRC="$(cd "$(dirname "$0")" && pwd)"

# Persistent venv lives under Application Support so reinstalling
# Heirloom.app doesn't trash it.
APP_SUPPORT="$HOME/Library/Application Support/Heirloom"
TTS_HOME="$APP_SUPPORT/tts"
VENV="$TTS_HOME/venv"

mkdir -p "$TTS_HOME"

# 1. Pick a Python 3.11+ interpreter ------------------------------------
heading "Python"
PY=""
for cand in python3.13 python3.12 python3.11 python3; do
  if command -v "$cand" >/dev/null 2>&1; then
    v="$($cand -c 'import sys;print("%d.%d"%sys.version_info[:2])' 2>/dev/null || true)"
    case "$v" in
      3.11|3.12|3.13|3.14) PY="$cand"; break ;;
    esac
  fi
done
if [[ -z "$PY" ]]; then
  fail "No Python 3.11+ found. Install with: brew install python@3.12"
fi
ok "using $($PY --version)"

# 2. Create venv --------------------------------------------------------
heading "Virtual environment"
if [[ ! -d "$VENV" ]]; then
  "$PY" -m venv "$VENV"
  ok "venv at $VENV"
else
  ok "venv already present, reusing"
fi

# shellcheck disable=SC1091
source "$VENV/bin/activate"
python -m pip install --upgrade pip wheel >/dev/null
ok "pip upgraded"

# 3. Copy the sidecar source into TTS_HOME ------------------------------
heading "Sidecar source"
cp -f "$TTS_SRC/server.py" "$TTS_HOME/server.py"
cp -f "$TTS_SRC/requirements.txt" "$TTS_HOME/requirements.txt"
ok "server.py + requirements.txt staged"

# 4. Install dependencies ----------------------------------------------
heading "Dependencies (this can take 5–10 minutes)"
pip install -r "$TTS_HOME/requirements.txt"
# LuxTTS + LinaCodec are git installs; piper-phonemize needs the icefall
# wheel index. Order matters - see infra/tts-server/README.md.
pip install --find-links https://k2-fsa.github.io/icefall/piper_phonemize.html piper-phonemize || true
pip install "git+https://github.com/ysharma3501/LinaCodec.git"
pip install "git+https://github.com/ysharma3501/LuxTTS.git"
ok "deps installed"

# 5. Smoke-test the import ---------------------------------------------
heading "Smoke test"
python -c "import torch, fastapi, soundfile, librosa; from zipvoice.luxvoice import LuxTTS; print('imports ok')"
ok "core imports succeed"

# 6. Write a tiny launcher Heirloom can exec ---------------------------
cat > "$TTS_HOME/run.sh" <<EOF
#!/usr/bin/env bash
# Auto-generated by install-tts.sh. Heirloom's Rust shell execs this.
set -euo pipefail
export HEIRLOOM_VOICE_DIR="$APP_SUPPORT/voice"
mkdir -p "\$HEIRLOOM_VOICE_DIR"
cd "$TTS_HOME"
exec "$VENV/bin/python" "$TTS_HOME/server.py"
EOF
chmod +x "$TTS_HOME/run.sh"
ok "launcher at $TTS_HOME/run.sh"

heading "Done"
echo "  Quit and relaunch Heirloom - voice cloning will be available."
